
# This is a basic workflow to help you get started with Actions

name: GCP-GITHUB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Get_OIDC_ID_token:
    runs-on: self-hosted
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.8.1'
      with:
          create_credentials_file: true
          export_environment_variables: true
          workload_identity_provider: 'projects/529797684709/locations/global/workloadIdentityPools/test-gh-self-runner/providers/github'
          service_account: 'test-gh-self-runner@game-sandbox-308006.iam.gserviceaccount.com'
#           credentials_json: '${{ secrets.GOOGLE_SECRET }}'
  
#     - id: 'gcloud'
#       name: 'gcloud'
#       run: |-
#         gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
#         gcloud container clusters list
#         gcloud compute instances list 
  
    - id: get-gke-credentials
      uses: google-github-actions/get-gke-credentials@v0.8.0
      with:
        project_id: game-sandbox-308006
        cluster_name: sbx-usw1
        location: us-west1
#         use_internal_ip: true

    - id: get-ns
      run: kubectl get namespaces
